import { Template } from "@/lib/types";

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: "blank",
    name: "Blank",
    description: "Start from scratch with a clean canvas",
    category: "Basic",
    tags: ["blank", "empty", "custom"],
    previewColor: "#1e1b4b",
    screens: [
      {
        name: "Screen 1",
        background: {
          type: "gradient",
          gradient: {
            direction: "to-br",
            stops: [
              { color: "#6366f1", position: 0 },
              { color: "#8b5cf6", position: 100 },
            ],
          },
        },
        layers: [],
      },
    ],
  },
  {
    id: "fitness",
    name: "Fitness App",
    description: "Bold and energetic layout for fitness and workout apps",
    category: "Health",
    tags: ["fitness", "workout", "sport", "health"],
    previewColor: "#052e16",
    screens: [
      {
        name: "Hero",
        background: {
          type: "gradient",
          gradient: {
            direction: "to-br",
            stops: [
              { color: "#065f46", position: 0 },
              { color: "#10b981", position: 100 },
            ],
          },
        },
        layers: [
          {
            type: "text",
            content: "Track Every\nRep & Run",
            x: 80,
            y: 300,
            width: 900,
            height: 300,
            fontSize: 120,
            fontFamily: "Geist Sans",
            fontWeight: 800,
            color: "#ffffff",
            align: "left",
            lineHeight: 1.1,
            letterSpacing: -2,
            rotation: 0,
            opacity: 1,
          },
          {
            type: "text",
            content: "Your AI-powered fitness companion",
            x: 80,
            y: 640,
            width: 900,
            height: 100,
            fontSize: 52,
            fontFamily: "Geist Sans",
            fontWeight: 400,
            color: "rgba(255,255,255,0.75)",
            align: "left",
            lineHeight: 1.4,
            letterSpacing: 0,
            rotation: 0,
            opacity: 1,
          },
        ],
      },
    ],
  },
  {
    id: "finance",
    name: "Finance & Crypto",
    description: "Sleek dark theme for finance, banking and crypto apps",
    category: "Finance",
    tags: ["finance", "crypto", "banking", "money", "wallet"],
    previewColor: "#0c0a09",
    screens: [
      {
        name: "Dashboard",
        background: {
          type: "gradient",
          gradient: {
            direction: "to-b",
            stops: [
              { color: "#0f172a", position: 0 },
              { color: "#1e293b", position: 100 },
            ],
          },
        },
        layers: [
          {
            type: "text",
            content: "Your Money.\nYour Rules.",
            x: 80,
            y: 280,
            width: 900,
            height: 280,
            fontSize: 120,
            fontFamily: "Geist Sans",
            fontWeight: 700,
            color: "#f8fafc",
            align: "left",
            lineHeight: 1.1,
            letterSpacing: -2,
            rotation: 0,
            opacity: 1,
          },
          {
            type: "text",
            content: "Manage crypto & stocks in one place",
            x: 80,
            y: 600,
            width: 900,
            height: 100,
            fontSize: 50,
            fontFamily: "Geist Sans",
            fontWeight: 400,
            color: "rgba(148,163,184,0.9)",
            align: "left",
            lineHeight: 1.4,
            letterSpacing: 0,
            rotation: 0,
            opacity: 1,
          },
        ],
      },
    ],
  },
  {
    id: "travel",
    name: "Travel & Adventure",
    description: "Beautiful vibrant layout for travel and discovery apps",
    category: "Lifestyle",
    tags: ["travel", "adventure", "maps", "tourism"],
    previewColor: "#082f49",
    screens: [
      {
        name: "Explore",
        background: {
          type: "gradient",
          gradient: {
            direction: "to-br",
            stops: [
              { color: "#0c4a6e", position: 0 },
              { color: "#0891b2", position: 100 },
            ],
          },
        },
        layers: [
          {
            type: "text",
            content: "Discover\nNew Places",
            x: 80,
            y: 280,
            width: 900,
            height: 280,
            fontSize: 120,
            fontFamily: "Geist Sans",
            fontWeight: 800,
            color: "#ffffff",
            align: "left",
            lineHeight: 1.1,
            letterSpacing: -2,
            rotation: 0,
            opacity: 1,
          },
          {
            type: "text",
            content: "Explore 10,000+ destinations worldwide",
            x: 80,
            y: 600,
            width: 900,
            height: 100,
            fontSize: 50,
            fontFamily: "Geist Sans",
            fontWeight: 400,
            color: "rgba(255,255,255,0.8)",
            align: "left",
            lineHeight: 1.4,
            letterSpacing: 0,
            rotation: 0,
            opacity: 1,
          },
        ],
      },
    ],
  },
  {
    id: "productivity",
    name: "Productivity & Notes",
    description: "Clean minimal layout for task managers and note apps",
    category: "Productivity",
    tags: ["productivity", "notes", "tasks", "todo", "minimal"],
    previewColor: "#fffbeb",
    screens: [
      {
        name: "Main",
        background: {
          type: "gradient",
          gradient: {
            direction: "to-br",
            stops: [
              { color: "#fef3c7", position: 0 },
              { color: "#fde68a", position: 100 },
            ],
          },
        },
        layers: [
          {
            type: "text",
            content: "Get More\nDone Today",
            x: 80,
            y: 280,
            width: 900,
            height: 280,
            fontSize: 120,
            fontFamily: "Geist Sans",
            fontWeight: 800,
            color: "#1c1917",
            align: "left",
            lineHeight: 1.1,
            letterSpacing: -2,
            rotation: 0,
            opacity: 1,
          },
          {
            type: "text",
            content: "The smarter way to organize your day",
            x: 80,
            y: 600,
            width: 900,
            height: 100,
            fontSize: 50,
            fontFamily: "Geist Sans",
            fontWeight: 400,
            color: "rgba(28,25,23,0.7)",
            align: "left",
            lineHeight: 1.4,
            letterSpacing: 0,
            rotation: 0,
            opacity: 1,
          },
        ],
      },
    ],
  },
  {
    id: "social",
    name: "Social & Community",
    description: "Vibrant layout for social networking and community apps",
    category: "Social",
    tags: ["social", "community", "chat", "messaging", "friends"],
    previewColor: "#4a044e",
    screens: [
      {
        name: "Connect",
        background: {
          type: "gradient",
          gradient: {
            direction: "to-br",
            stops: [
              { color: "#7e22ce", position: 0 },
              { color: "#db2777", position: 100 },
            ],
          },
        },
        layers: [
          {
            type: "text",
            content: "Connect &\nGrow Together",
            x: 80,
            y: 280,
            width: 900,
            height: 280,
            fontSize: 112,
            fontFamily: "Geist Sans",
            fontWeight: 800,
            color: "#ffffff",
            align: "left",
            lineHeight: 1.1,
            letterSpacing: -2,
            rotation: 0,
            opacity: 1,
          },
          {
            type: "text",
            content: "Join millions sharing their passion",
            x: 80,
            y: 600,
            width: 900,
            height: 100,
            fontSize: 50,
            fontFamily: "Geist Sans",
            fontWeight: 400,
            color: "rgba(255,255,255,0.8)",
            align: "left",
            lineHeight: 1.4,
            letterSpacing: 0,
            rotation: 0,
            opacity: 1,
          },
        ],
      },
    ],
  },
  {
    id: "ecommerce",
    name: "E-Commerce & Shopping",
    description: "Modern shopping layout with product showcases",
    category: "Shopping",
    tags: ["ecommerce", "shopping", "store", "marketplace"],
    previewColor: "#fff1f2",
    screens: [
      {
        name: "Shop",
        background: {
          type: "gradient",
          gradient: {
            direction: "to-b",
            stops: [
              { color: "#fff1f2", position: 0 },
              { color: "#fecdd3", position: 100 },
            ],
          },
        },
        layers: [
          {
            type: "text",
            content: "Shop Smarter,\nLive Better",
            x: 80,
            y: 280,
            width: 900,
            height: 280,
            fontSize: 112,
            fontFamily: "Geist Sans",
            fontWeight: 800,
            color: "#881337",
            align: "left",
            lineHeight: 1.1,
            letterSpacing: -2,
            rotation: 0,
            opacity: 1,
          },
          {
            type: "text",
            content: "1M+ products delivered to your door",
            x: 80,
            y: 600,
            width: 900,
            height: 100,
            fontSize: 50,
            fontFamily: "Geist Sans",
            fontWeight: 400,
            color: "rgba(136,19,55,0.7)",
            align: "left",
            lineHeight: 1.4,
            letterSpacing: 0,
            rotation: 0,
            opacity: 1,
          },
        ],
      },
    ],
  },
  {
    id: "music",
    name: "Music & Podcasts",
    description: "Dark immersive layout for music players and podcast apps",
    category: "Entertainment",
    tags: ["music", "podcast", "audio", "player", "streaming"],
    previewColor: "#030712",
    screens: [
      {
        name: "Player",
        background: {
          type: "gradient",
          gradient: {
            direction: "to-b",
            stops: [
              { color: "#030712", position: 0 },
              { color: "#1d1117", position: 60 },
              { color: "#0f0f1a", position: 100 },
            ],
          },
        },
        layers: [
          {
            type: "text",
            content: "Feel the\nBeat",
            x: 80,
            y: 280,
            width: 900,
            height: 280,
            fontSize: 140,
            fontFamily: "Geist Sans",
            fontWeight: 900,
            color: "#ffffff",
            align: "left",
            lineHeight: 1.0,
            letterSpacing: -4,
            rotation: 0,
            opacity: 1,
          },
          {
            type: "text",
            content: "100M+ songs & podcasts in your pocket",
            x: 80,
            y: 600,
            width: 900,
            height: 100,
            fontSize: 48,
            fontFamily: "Geist Sans",
            fontWeight: 400,
            color: "rgba(255,255,255,0.6)",
            align: "left",
            lineHeight: 1.4,
            letterSpacing: 0,
            rotation: 0,
            opacity: 1,
          },
        ],
      },
    ],
  },
  {
    id: "gaming",
    name: "Gaming",
    description: "Dark neon layout for mobile games and gaming platforms",
    category: "Entertainment",
    tags: ["gaming", "game", "neon", "dark", "leaderboard"],
    previewColor: "#020617",
    screens: [
      {
        name: "Lobby",
        background: {
          type: "gradient",
          gradient: {
            direction: "to-br",
            stops: [
              { color: "#020617", position: 0 },
              { color: "#0f172a", position: 50 },
              { color: "#1e0a3c", position: 100 },
            ],
          },
        },
        layers: [
          {
            type: "text",
            content: "Level Up\nYour Game",
            x: 80,
            y: 280,
            width: 900,
            height: 280,
            fontSize: 120,
            fontFamily: "Geist Sans",
            fontWeight: 900,
            color: "#a855f7",
            align: "left",
            lineHeight: 1.1,
            letterSpacing: -2,
            rotation: 0,
            opacity: 1,
          },
          {
            type: "text",
            content: "Compete. Win. Dominate the leaderboard.",
            x: 80,
            y: 600,
            width: 900,
            height: 100,
            fontSize: 48,
            fontFamily: "Geist Sans",
            fontWeight: 400,
            color: "rgba(168,85,247,0.7)",
            align: "left",
            lineHeight: 1.4,
            letterSpacing: 0,
            rotation: 0,
            opacity: 1,
          },
        ],
      },
    ],
  },
  {
    id: "dating",
    name: "Dating App",
    description: "Vibrant romantic layout for dating and social apps",
    category: "Social",
    tags: ["dating", "social", "love", "match"],
    previewColor: "#4c0519",
    screens: [
      {
        name: "Match",
        background: {
          type: "gradient",
          gradient: {
            direction: "to-br",
            stops: [
              { color: "#be123c", position: 0 },
              { color: "#f43f5e", position: 60 },
              { color: "#fb7185", position: 100 },
            ],
          },
        },
        layers: [
          {
            type: "text",
            content: "Find Your\nPerfect Match",
            x: 80,
            y: 280,
            width: 900,
            height: 280,
            fontSize: 112,
            fontFamily: "Geist Sans",
            fontWeight: 800,
            color: "#ffffff",
            align: "left",
            lineHeight: 1.1,
            letterSpacing: -2,
            rotation: 0,
            opacity: 1,
          },
          {
            type: "text",
            content: "Real connections. Real people. Real love.",
            x: 80,
            y: 600,
            width: 900,
            height: 100,
            fontSize: 48,
            fontFamily: "Geist Sans",
            fontWeight: 400,
            color: "rgba(255,255,255,0.85)",
            align: "left",
            lineHeight: 1.4,
            letterSpacing: 0,
            rotation: 0,
            opacity: 1,
          },
        ],
      },
    ],
  },
];

export const TEMPLATE_CATEGORIES = [
  "All",
  "Basic",
  "Health",
  "Finance",
  "Lifestyle",
  "Productivity",
  "Social",
  "Shopping",
  "Entertainment",
];
