import { Theme, ThemeId, ThemeCategory, SlideLayout } from "./types";

export const DEFAULT_THEME_ID: ThemeId = "clean-light";

export const THEME_CATEGORIES: { id: ThemeCategory; label: string; count?: number }[] = [
  { id: "all", label: "All Themes" },
  { id: "light", label: "Light & Clean" },
  { id: "dark", label: "Dark & AMOLED" },
  { id: "vibrant", label: "Vibrant & Bold" },
  { id: "pastel", label: "Pastel & Soft" },
  { id: "earthy", label: "Earthy & Warm" },
  { id: "neon", label: "Neon & Cyber" },
  { id: "gradient", label: "Gradients" },
];

export const THEMES: Record<ThemeId, Theme> = {
  // ── 1. LIGHT & CLEAN (10) ────────────────────────────────────────────────
  "clean-light": {
    id: "clean-light",
    name: "Clean Light",
    category: "light",
    bg: "#F6F1EA",
    bgAlt: "#171717",
    fg: "#171717",
    fgAlt: "#F6F1EA",
    accent: "#5B7CFA",
    muted: "#6B7280",
  },
  "pure-white": {
    id: "pure-white",
    name: "Pure Minimal",
    category: "light",
    bg: "#FFFFFF",
    bgAlt: "#0F172A",
    fg: "#0F172A",
    fgAlt: "#FFFFFF",
    accent: "#3B82F6",
    muted: "#64748B",
  },
  "soft-linen": {
    id: "soft-linen",
    name: "Soft Linen",
    category: "light",
    bg: "#FAF8F5",
    bgAlt: "#262626",
    fg: "#262626",
    fgAlt: "#FAF8F5",
    accent: "#E11D48",
    muted: "#737373",
  },
  "nordic-snow": {
    id: "nordic-snow",
    name: "Nordic Snow",
    category: "light",
    bg: "#F8FAFC",
    bgAlt: "#0F172A",
    fg: "#0F172A",
    fgAlt: "#F8FAFC",
    accent: "#0EA5E9",
    muted: "#64748B",
  },
  "ivory-cloud": {
    id: "ivory-cloud",
    name: "Ivory Cloud",
    category: "light",
    bg: "#FFFDF9",
    bgAlt: "#1C1917",
    fg: "#1C1917",
    fgAlt: "#FFFDF9",
    accent: "#F59E0B",
    muted: "#78716C",
  },
  "silver-sage": {
    id: "silver-sage",
    name: "Silver Sage",
    category: "light",
    bg: "#F0FDF4",
    bgAlt: "#14532D",
    fg: "#14532D",
    fgAlt: "#F0FDF4",
    accent: "#22C55E",
    muted: "#4B7C5E",
  },
  "paper-sheet": {
    id: "paper-sheet",
    name: "Paper White",
    category: "light",
    bg: "#F4F4F5",
    bgAlt: "#18181B",
    fg: "#18181B",
    fgAlt: "#F4F4F5",
    accent: "#6366F1",
    muted: "#71717A",
  },
  "porcelain": {
    id: "porcelain",
    name: "Porcelain Blue",
    category: "light",
    bg: "#EFF6FF",
    bgAlt: "#1E3A8A",
    fg: "#1E3A8A",
    fgAlt: "#EFF6FF",
    accent: "#2563EB",
    muted: "#60A5FA",
  },
  "studio-slate": {
    id: "studio-slate",
    name: "Studio Slate",
    category: "light",
    bg: "#F1F5F9",
    bgAlt: "#334155",
    fg: "#1E293B",
    fgAlt: "#F1F5F9",
    accent: "#475569",
    muted: "#64748B",
  },
  "warm-cream": {
    id: "warm-cream",
    name: "Warm Cream",
    category: "light",
    bg: "#FEFCE8",
    bgAlt: "#713F12",
    fg: "#713F12",
    fgAlt: "#FEFCE8",
    accent: "#CA8A04",
    muted: "#A16207",
  },

  // ── 2. DARK & AMOLED (10) ────────────────────────────────────────────────
  "dark-bold": {
    id: "dark-bold",
    name: "Dark Bold",
    category: "dark",
    bg: "#0B1020",
    bgAlt: "#F8FAFC",
    fg: "#F8FAFC",
    fgAlt: "#0B1020",
    accent: "#8B5CF6",
    muted: "#94A3B8",
  },
  "amoled-pitch": {
    id: "amoled-pitch",
    name: "AMOLED Pitch Black",
    category: "dark",
    bg: "#000000",
    bgAlt: "#FFFFFF",
    fg: "#FFFFFF",
    fgAlt: "#000000",
    accent: "#38BDF8",
    muted: "#A1A1AA",
  },
  "midnight-navy": {
    id: "midnight-navy",
    name: "Midnight Navy",
    category: "dark",
    bg: "#0A1128",
    bgAlt: "#E2E8F0",
    fg: "#F8FAFC",
    fgAlt: "#0A1128",
    accent: "#60A5FA",
    muted: "#94A3B8",
  },
  "charcoal-matte": {
    id: "charcoal-matte",
    name: "Charcoal Matte",
    category: "dark",
    bg: "#18181B",
    bgAlt: "#FAFAFA",
    fg: "#FAFAFA",
    fgAlt: "#18181B",
    accent: "#A1A1AA",
    muted: "#71717A",
  },
  "deep-obsidian": {
    id: "deep-obsidian",
    name: "Deep Obsidian",
    category: "dark",
    bg: "#0F172A",
    bgAlt: "#F1F5F9",
    fg: "#F8FAFC",
    fgAlt: "#0F172A",
    accent: "#38BDF8",
    muted: "#94A3B8",
  },
  "space-cadet": {
    id: "space-cadet",
    name: "Space Cadet",
    category: "dark",
    bg: "#1A1A2E",
    bgAlt: "#EAEAEA",
    fg: "#FFFFFF",
    fgAlt: "#1A1A2E",
    accent: "#E94560",
    muted: "#A2A8D3",
  },
  "carbon-dark": {
    id: "carbon-dark",
    name: "Carbon Dark",
    category: "dark",
    bg: "#121212",
    bgAlt: "#EEEEEE",
    fg: "#F3F4F6",
    fgAlt: "#121212",
    accent: "#BB86FC",
    muted: "#9CA3AF",
  },
  "eclipse-purple": {
    id: "eclipse-purple",
    name: "Eclipse Purple",
    category: "dark",
    bg: "#160D27",
    bgAlt: "#F3E8FF",
    fg: "#FAF5FF",
    fgAlt: "#160D27",
    accent: "#C084FC",
    muted: "#A855F7",
  },
  "titanium-metal": {
    id: "titanium-metal",
    name: "Titanium Metal",
    category: "dark",
    bg: "#212529",
    bgAlt: "#F8F9FA",
    fg: "#F8F9FA",
    fgAlt: "#212529",
    accent: "#CED4DA",
    muted: "#6C757D",
  },
  "dark-emerald": {
    id: "dark-emerald",
    name: "Deep Emerald Dark",
    category: "dark",
    bg: "#06281E",
    bgAlt: "#ECFDF5",
    fg: "#ECFDF5",
    fgAlt: "#06281E",
    accent: "#34D399",
    muted: "#6EE7B7",
  },

  // ── 3. VIBRANT & BOLD (10) ───────────────────────────────────────────────
  "sunset-glow": {
    id: "sunset-glow",
    name: "Sunset Coral",
    category: "vibrant",
    bg: "#FF5964",
    bgAlt: "#FFFFFF",
    fg: "#FFFFFF",
    fgAlt: "#FF5964",
    accent: "#FFE66D",
    muted: "#FFE5D9",
  },
  "electric-violet": {
    id: "electric-violet",
    name: "Electric Violet",
    category: "vibrant",
    bg: "#7C3AED",
    bgAlt: "#FFFFFF",
    fg: "#FFFFFF",
    fgAlt: "#7C3AED",
    accent: "#FDE047",
    muted: "#DDD6FE",
  },
  "tropical-punch": {
    id: "tropical-punch",
    name: "Tropical Punch",
    category: "vibrant",
    bg: "#FF006E",
    bgAlt: "#FFFFFF",
    fg: "#FFFFFF",
    fgAlt: "#FF006E",
    accent: "#FFBE0B",
    muted: "#FFD6EC",
  },
  "coral-blaze": {
    id: "coral-blaze",
    name: "Coral Blaze",
    category: "vibrant",
    bg: "#F97316",
    bgAlt: "#FFFFFF",
    fg: "#FFFFFF",
    fgAlt: "#F97316",
    accent: "#FEF08A",
    muted: "#FFEDD5",
  },
  "emerald-rush": {
    id: "emerald-rush",
    name: "Emerald Rush",
    category: "vibrant",
    bg: "#059669",
    bgAlt: "#FFFFFF",
    fg: "#FFFFFF",
    fgAlt: "#059669",
    accent: "#6EE7B7",
    muted: "#D1FAE5",
  },
  "royal-indigo": {
    id: "royal-indigo",
    name: "Royal Indigo",
    category: "vibrant",
    bg: "#4338CA",
    bgAlt: "#FFFFFF",
    fg: "#FFFFFF",
    fgAlt: "#4338CA",
    accent: "#93C5FD",
    muted: "#E0E7FF",
  },
  "citrus-sun": {
    id: "citrus-sun",
    name: "Citrus Sun",
    category: "vibrant",
    bg: "#FBBF24",
    bgAlt: "#18181B",
    fg: "#18181B",
    fgAlt: "#FBBF24",
    accent: "#D97706",
    muted: "#78350F",
  },
  "hot-magenta": {
    id: "hot-magenta",
    name: "Hot Magenta",
    category: "vibrant",
    bg: "#D946EF",
    bgAlt: "#FFFFFF",
    fg: "#FFFFFF",
    fgAlt: "#D946EF",
    accent: "#FDE047",
    muted: "#FAE8FF",
  },
  "ocean-fresh": {
    id: "ocean-fresh",
    name: "Ocean Fresh",
    category: "vibrant",
    bg: "#0284C7",
    bgAlt: "#FFFFFF",
    fg: "#FFFFFF",
    fgAlt: "#0284C7",
    accent: "#BAE6FD",
    muted: "#E0F2FE",
  },
  "hyper-teal": {
    id: "hyper-teal",
    name: "Hyper Teal",
    category: "vibrant",
    bg: "#0D9488",
    bgAlt: "#FFFFFF",
    fg: "#FFFFFF",
    fgAlt: "#0D9488",
    accent: "#99F6E4",
    muted: "#CCFBF1",
  },

  // ── 4. PASTEL & SOFT (10) ────────────────────────────────────────────────
  "matcha-latte": {
    id: "matcha-latte",
    name: "Matcha Latte",
    category: "pastel",
    bg: "#D8F3DC",
    bgAlt: "#1B4332",
    fg: "#1B4332",
    fgAlt: "#D8F3DC",
    accent: "#52B788",
    muted: "#40916C",
  },
  "lavender-dream": {
    id: "lavender-dream",
    name: "Lavender Dream",
    category: "pastel",
    bg: "#EDE9FE",
    bgAlt: "#4C1D95",
    fg: "#4C1D95",
    fgAlt: "#EDE9FE",
    accent: "#8B5CF6",
    muted: "#6D28D9",
  },
  "peach-sorbet": {
    id: "peach-sorbet",
    name: "Peach Sorbet",
    category: "pastel",
    bg: "#FFEDD5",
    bgAlt: "#7C2D12",
    fg: "#7C2D12",
    fgAlt: "#FFEDD5",
    accent: "#FB923C",
    muted: "#9A3412",
  },
  "bubblegum": {
    id: "bubblegum",
    name: "Bubblegum Pink",
    category: "pastel",
    bg: "#FCE7F3",
    bgAlt: "#831843",
    fg: "#831843",
    fgAlt: "#FCE7F3",
    accent: "#EC4899",
    muted: "#BE185D",
  },
  "mint-frost": {
    id: "mint-frost",
    name: "Mint Frost",
    category: "pastel",
    bg: "#CCFBF1",
    bgAlt: "#115E59",
    fg: "#115E59",
    fgAlt: "#CCFBF1",
    accent: "#14B8A6",
    muted: "#0F766E",
  },
  "buttercream": {
    id: "buttercream",
    name: "Buttercream",
    category: "pastel",
    bg: "#FEF9C3",
    bgAlt: "#713F12",
    fg: "#713F12",
    fgAlt: "#FEF9C3",
    accent: "#EAB308",
    muted: "#854D0E",
  },
  "baby-blue": {
    id: "baby-blue",
    name: "Baby Sky Blue",
    category: "pastel",
    bg: "#E0F2FE",
    bgAlt: "#075985",
    fg: "#075985",
    fgAlt: "#E0F2FE",
    accent: "#38BDF8",
    muted: "#0284C7",
  },
  "lilac-mist": {
    id: "lilac-mist",
    name: "Lilac Mist",
    category: "pastel",
    bg: "#F3E8FF",
    bgAlt: "#581C87",
    fg: "#581C87",
    fgAlt: "#F3E8FF",
    accent: "#A855F7",
    muted: "#7E22CE",
  },
  "rose-quartz": {
    id: "rose-quartz",
    name: "Rose Quartz",
    category: "pastel",
    bg: "#FFE4E6",
    bgAlt: "#881337",
    fg: "#881337",
    fgAlt: "#FFE4E6",
    accent: "#F43F5E",
    muted: "#BE123C",
  },
  "apricot-glow": {
    id: "apricot-glow",
    name: "Apricot Cream",
    category: "pastel",
    bg: "#FFF1E6",
    bgAlt: "#9A3412",
    fg: "#7C2D12",
    fgAlt: "#FFF1E6",
    accent: "#F97316",
    muted: "#C2410C",
  },

  // ── 5. EARTHY & WARM (10) ────────────────────────────────────────────────
  "warm-editorial": {
    id: "warm-editorial",
    name: "Warm Editorial",
    category: "earthy",
    bg: "#F7E8DA",
    bgAlt: "#2B1D17",
    fg: "#2B1D17",
    fgAlt: "#F7E8DA",
    accent: "#D97706",
    muted: "#7C5A47",
  },
  "bloom-roast": {
    id: "bloom-roast",
    name: "Bloom Roast",
    category: "earthy",
    bg: "#F2ECE2",
    bgAlt: "#24352F",
    fg: "#1D2420",
    fgAlt: "#FFF7EA",
    accent: "#B8794A",
    muted: "#65736B",
  },
  "terracotta": {
    id: "terracotta",
    name: "Terracotta Clay",
    category: "earthy",
    bg: "#C2410C",
    bgAlt: "#FFF7ED",
    fg: "#FFF7ED",
    fgAlt: "#C2410C",
    accent: "#FDBA74",
    muted: "#FED7AA",
  },
  "sandstone": {
    id: "sandstone",
    name: "Sandstone Dune",
    category: "earthy",
    bg: "#E7E5E4",
    bgAlt: "#292524",
    fg: "#292524",
    fgAlt: "#E7E5E4",
    accent: "#78716C",
    muted: "#57534E",
  },
  "olive-grove": {
    id: "olive-grove",
    name: "Olive Grove",
    category: "earthy",
    bg: "#365314",
    bgAlt: "#ECFCCB",
    fg: "#ECFCCB",
    fgAlt: "#365314",
    accent: "#A3E635",
    muted: "#BEF264",
  },
  "desert-sand": {
    id: "desert-sand",
    name: "Desert Ochre",
    category: "earthy",
    bg: "#D97706",
    bgAlt: "#FFFFFF",
    fg: "#FFFFFF",
    fgAlt: "#D97706",
    accent: "#FEF3C7",
    muted: "#FDE68A",
  },
  "coffee-bean": {
    id: "coffee-bean",
    name: "Espresso Brown",
    category: "earthy",
    bg: "#3E2723",
    bgAlt: "#EFEBE9",
    fg: "#EFEBE9",
    fgAlt: "#3E2723",
    accent: "#D7CCC8",
    muted: "#BCAAA4",
  },
  "tuscan-sun": {
    id: "tuscan-sun",
    name: "Tuscan Autumn",
    category: "earthy",
    bg: "#78350F",
    bgAlt: "#FEF3C7",
    fg: "#FEF3C7",
    fgAlt: "#78350F",
    accent: "#FBBF24",
    muted: "#FDE68A",
  },
  "forest-pine": {
    id: "forest-pine",
    name: "Forest Pine",
    category: "earthy",
    bg: "#064E3B",
    bgAlt: "#ECFDF5",
    fg: "#ECFDF5",
    fgAlt: "#064E3B",
    accent: "#34D399",
    muted: "#A7F3D0",
  },
  "sage-moss": {
    id: "sage-moss",
    name: "Sage Moss",
    category: "earthy",
    bg: "#2E4036",
    bgAlt: "#E6EDE8",
    fg: "#E6EDE8",
    fgAlt: "#2E4036",
    accent: "#8FAF9B",
    muted: "#B2C5BA",
  },

  // ── 6. NEON & CYBER (6) ──────────────────────────────────────────────────
  "neon-matrix": {
    id: "neon-matrix",
    name: "Neon Matrix",
    category: "neon",
    bg: "#0D1117",
    bgAlt: "#00FF66",
    fg: "#00FF66",
    fgAlt: "#0D1117",
    accent: "#00CC52",
    muted: "#80FFB3",
  },
  "cyber-pink": {
    id: "cyber-pink",
    name: "Cyberpunk Pink",
    category: "neon",
    bg: "#10002B",
    bgAlt: "#FF007F",
    fg: "#FF007F",
    fgAlt: "#10002B",
    accent: "#00F5D4",
    muted: "#FF80BF",
  },
  "laser-cyan": {
    id: "laser-cyan",
    name: "Laser Cyan",
    category: "neon",
    bg: "#041C32",
    bgAlt: "#00FFF5",
    fg: "#00FFF5",
    fgAlt: "#041C32",
    accent: "#00B4D8",
    muted: "#80FFF8",
  },
  "volt-yellow": {
    id: "volt-yellow",
    name: "Volt Yellow",
    category: "neon",
    bg: "#000000",
    bgAlt: "#CCFF00",
    fg: "#CCFF00",
    fgAlt: "#000000",
    accent: "#99FF00",
    muted: "#E5FF80",
  },
  "tokyo-night": {
    id: "tokyo-night",
    name: "Tokyo Night",
    category: "neon",
    bg: "#1A1B26",
    bgAlt: "#7AA2F7",
    fg: "#7AA2F7",
    fgAlt: "#1A1B26",
    accent: "#BB9AF7",
    muted: "#A9B1D6",
  },
  "synthwave-80s": {
    id: "synthwave-80s",
    name: "Synthwave 84",
    category: "neon",
    bg: "#241734",
    bgAlt: "#FF71CE",
    fg: "#FF71CE",
    fgAlt: "#241734",
    accent: "#01CDFE",
    muted: "#B967FF",
  },

  // ── 7. MODERN GRADIENTS (12) ─────────────────────────────────────────────
  "aurora-borealis": {
    id: "aurora-borealis",
    name: "Aurora Borealis",
    category: "gradient",
    bg: "#0F2027",
    fg: "#FFFFFF",
    accent: "#2C5364",
    muted: "#94A3B8",
    gradient: {
      direction: "to-br",
      stops: [
        { color: "#0F2027", position: 0 },
        { color: "#203A43", position: 50 },
        { color: "#2C5364", position: 100 },
      ],
    },
  },
  "sunset-horizon": {
    id: "sunset-horizon",
    name: "Sunset Horizon",
    category: "gradient",
    bg: "#FF512F",
    fg: "#FFFFFF",
    accent: "#DD2476",
    muted: "#FFE4E6",
    gradient: {
      direction: "to-br",
      stops: [
        { color: "#FF512F", position: 0 },
        { color: "#DD2476", position: 100 },
      ],
    },
  },
  "ocean-breeze": {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    category: "gradient",
    bg: "#2B5876",
    fg: "#FFFFFF",
    accent: "#4E4376",
    muted: "#E2E8F0",
    gradient: {
      direction: "to-b",
      stops: [
        { color: "#2B5876", position: 0 },
        { color: "#4E4376", position: 100 },
      ],
    },
  },
  "purple-haze": {
    id: "purple-haze",
    name: "Purple Haze",
    category: "gradient",
    bg: "#654EA3",
    fg: "#FFFFFF",
    accent: "#EAAFC8",
    muted: "#F3E8FF",
    gradient: {
      direction: "to-br",
      stops: [
        { color: "#654EA3", position: 0 },
        { color: "#EAAFC8", position: 100 },
      ],
    },
  },
  "citrus-sunrise": {
    id: "citrus-sunrise",
    name: "Citrus Sunrise",
    category: "gradient",
    bg: "#FA709A",
    fg: "#FFFFFF",
    accent: "#FEE140",
    muted: "#FFF1F2",
    gradient: {
      direction: "to-br",
      stops: [
        { color: "#FA709A", position: 0 },
        { color: "#FEE140", position: 100 },
      ],
    },
  },
  "berry-smoothie": {
    id: "berry-smoothie",
    name: "Berry Blast",
    category: "gradient",
    bg: "#8E2DE2",
    fg: "#FFFFFF",
    accent: "#4A00E0",
    muted: "#DDD6FE",
    gradient: {
      direction: "to-br",
      stops: [
        { color: "#8E2DE2", position: 0 },
        { color: "#4A00E0", position: 100 },
      ],
    },
  },
  "emerald-wave": {
    id: "emerald-wave",
    name: "Emerald Wave",
    category: "gradient",
    bg: "#0BA360",
    fg: "#FFFFFF",
    accent: "#3CBA92",
    muted: "#D1FAE5",
    gradient: {
      direction: "to-br",
      stops: [
        { color: "#0BA360", position: 0 },
        { color: "#3CBA92", position: 100 },
      ],
    },
  },
  "cosmic-glow": {
    id: "cosmic-glow",
    name: "Cosmic Glow",
    category: "gradient",
    bg: "#1F1C2C",
    fg: "#FFFFFF",
    accent: "#928DAB",
    muted: "#CBD5E1",
    gradient: {
      direction: "to-br",
      stops: [
        { color: "#1F1C2C", position: 0 },
        { color: "#928DAB", position: 100 },
      ],
    },
  },
  "mystic-twilight": {
    id: "mystic-twilight",
    name: "Mystic Twilight",
    category: "gradient",
    bg: "#2C3E50",
    fg: "#FFFFFF",
    accent: "#FD746C",
    muted: "#CBD5E1",
    gradient: {
      direction: "to-br",
      stops: [
        { color: "#2C3E50", position: 0 },
        { color: "#FD746C", position: 100 },
      ],
    },
  },
  "cotton-candy": {
    id: "cotton-candy",
    name: "Cotton Candy",
    category: "gradient",
    bg: "#FF9A9E",
    fg: "#2B1D17",
    accent: "#FECFEF",
    muted: "#5B21B6",
    gradient: {
      direction: "to-br",
      stops: [
        { color: "#FF9A9E", position: 0 },
        { color: "#FECFEF", position: 100 },
      ],
    },
  },
  "hyper-space": {
    id: "hyper-space",
    name: "Hyper Space",
    category: "gradient",
    bg: "#000428",
    fg: "#FFFFFF",
    accent: "#004E92",
    muted: "#93C5FD",
    gradient: {
      direction: "to-br",
      stops: [
        { color: "#000428", position: 0 },
        { color: "#004E92", position: 100 },
      ],
    },
  },
  "dark-nova": {
    id: "dark-nova",
    name: "Dark Nova",
    category: "gradient",
    bg: "#141E30",
    fg: "#FFFFFF",
    accent: "#243B55",
    muted: "#94A3B8",
    gradient: {
      direction: "to-br",
      stops: [
        { color: "#141E30", position: 0 },
        { color: "#243B55", position: 100 },
      ],
    },
  },
};

export function themeById(themeId: ThemeId | undefined): Theme {
  if (!themeId) return THEMES[DEFAULT_THEME_ID];
  return THEMES[themeId] || {
    id: themeId,
    name: "Custom Theme",
    bg: themeId.startsWith("#") ? themeId : "#171717",
    fg: "#FFFFFF",
  };
}

export function getAutoTextColor(bgColor: string): string {
  // If gradient or invalid, default to white
  if (!bgColor || !bgColor.startsWith("#") || bgColor.length < 7) return "#FFFFFF";
  const r = parseInt(bgColor.slice(1, 3), 16) || 0;
  const g = parseInt(bgColor.slice(3, 5), 16) || 0;
  const b = parseInt(bgColor.slice(5, 7), 16) || 0;
  // Calculate relative luminance
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance > 0.6 ? "#111827" : "#FFFFFF";
}

export const LAYOUT_LABEL: Record<SlideLayout, string> = {
  hero: "Hero",
  "device-bottom": "Device bottom",
  "device-top": "Device top",
  "two-devices": "Two devices",
  "no-device": "No device",
  "split-landscape": "Split (landscape)",
  "feature-graphic": "Feature graphic",
};

export const LAYOUT_HINT: Record<SlideLayout, string> = {
  hero: "Headline above, device at bottom",
  "device-bottom": "Headline top, device anchored below",
  "device-top": "Flipped — device on top",
  "two-devices": "Layered back + front phones",
  "no-device": "Big standalone headline",
  "split-landscape": "Caption left, device right",
  "feature-graphic": "1024×500 Play Store banner",
};
